# use latest LTS
FROM node:lts-alpine

# set working directory inside the container
WORKDIR /app

# copy package .json and package-lock.json
COPY package*.json ./

# install dep
RUN npm install 

# expose port 
EXPOSE 5173

