# use latest LTS
FROM node:lts-alpine

# set working directory inside the container
WORKDIR /app

# copy package .json and package-lock.json
COPY ./package.json ./

# install dep
RUN npm install 

COPY ./ ./

# expose port 
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
