
services:
  #nom du service
  frontend:
    # on indique le nom du dossier qui contient le dockerfile
    build: ./frontend
    #on indique le port à écouter
    ports:
      - 5173:5173

    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - ./node_modules
        - action: rebuild
          path: ./frontend/package.json
    # gère le partage de fichier entre l'hôte et le container
    # permet de synchroniser les fichier ou stocker des données
    # ici on bind les deux fichier pour avoir une synchro
    volumes:
      - ./frontend:/app
      # ignore les fichier de dependances
      - /app/node_modules
    # commande pour lancer le serveur de dev
    command: npm run dev